services:
    marttiphpbb.archiveforum.calendarautoarchive_listener:
        class: marttiphpbb\archiveforum\event\calendarautoarchive_listener
        arguments:
            - '@config'
        tags:
            - { name: event.listener }

    marttiphpbb.archiveforum.topiclist_listener:
        class: marttiphpbb\archiveforum\event\topiclist_listener
        arguments:
            - '@dbal.conn'
            - '%tables.topics%'
            - '%tables.forums%'
            - '@config'
            - '@auth'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }

    marttiphpbb.archiveforum.topic_listener:
        class: marttiphpbb\archiveforum\event\topic_listener
        arguments:
            - '@dbal.conn'
            - '%tables.topics%'
            - '%tables.forums%'
            - '@config'
            - '@auth'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@template'
        tags:
            - { name: event.listener }

    marttiphpbb.archiveforum.main_listener:
        class: marttiphpbb\archiveforum\event\main_listener
        tags:
            - { name: event.listener }

    marttiphpbb.archiveforum.mcp_topic_listener:
        class: marttiphpbb\archiveforum\event\mcp_topic_listener
        arguments:
            - '@dbal.conn'
            - '%tables.topics%'
            - '@config'
            - '@auth'
            - '@language'
            - '@request'
            - '@template'
        tags:
            - { name: event.listener }

    marttiphpbb.archiveforum.mcp_forum_listener:
        class: marttiphpbb\archiveforum\event\mcp_forum_listener
        arguments:
            - '@dbal.conn'
            - '%tables.topics%'
            - '%tables.forums%'
            - '@config'
            - '@auth'
            - '@language'
            - '@request'
            - '@template'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@log'
            - '@user'
        tags:
            - { name: event.listener }

    marttiphpbb.archiveforum.move_topic_listener:
        class: marttiphpbb\archiveforum\event\move_topic_listener
        arguments:
            - '@dbal.conn'
            - '%tables.topics%'
        tags:
            - { name: event.listener }
