services:
    marttiphpbb.archiveforum.listener:
        class: marttiphpbb\archiveforum\event\listener
        arguments:
            - '@dbal.conn'
            - '%tables.topics%'
        tags:
            - { name: event.listener }

