services:
    marttiphpbb.archiveforum.listener:
        class: marttiphpbb\archiveforum\event\listener
        arguments:
            - '@dbal.conn'
            - '%tables.topics%'
            - '@config'
            - '@auth'
        tags:
            - { name: event.listener }

